---
- name: Configure http
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Install httpd
    yum:
     name: httpd
     state: present

  - name: restart service
    service:
      name: httpd
      state: restarted
