---
- name: Configure nfs server
  hosts: localhost
  tasks:
   - name: Install nfs
     yum:
      name: nfs-utils
      state: present

   - name: Create a directory if it does not exist
     file:
       path: /root/nfsshare
       state: directory
       mode: '0755'
     

   - name: make entry in /etc/exports
     copy:
       content: '/root/nfsshare      *.example.com(rw,sync)'
       dest: /etc/exports

   - name: Restart nfs service
     service:
       name: nfs
       state: restarted


   - name: Add entry in firewall
     firewalld:
        service: nfs
        permanent: yes
        state: enabled


